export const GET_HOTEL_LIST = "ADD_HOTEL_LIST";
export const GET_HOTEL_DETAIL = "HOTEL_DETAIL";

export const SELECTED_HOTEL = "SELECTED_HOTEL";
export const ADD_ADULT_SIZE = "ADD_ADULTSIZE";
export const ADD_CHILD_SIZE = "ADD_CHILDSIZE";
export const ADD_ENTRY_DATE = "ADD_ENTRYDATE";
export const ADD_OUT_DATE   = "ADD_OUTDATE";
export const ADD_HOTEL_NAME = "ADD_HOTELNAME";
export const ADD_ROOM_TYPE = "ADD_ROOMTYPE";
export const ADD_ROOM_SCENIC = "ADD_ROOMSCENIC";
export const ADD_PRICE = "ADD_PRICE";
export const ADD_PRICE_RATE = "ADD_PRICERATE";
export const ADD_DISCOUNT_CODE_LIST = "ADD_DISCOUNTCODE";
export const ADD_CALCULATE_PRICE = "ADD_CALCULATEPRICE";
export const ADD_DISCOUNT_CODE_ERROR = "ADD_DISCOUNTCODE_ERROR";
export const ADD_ROOM_PRICE = "ADD_ROOMPRICE";
export const ADD_RESERVATION_RESPONSE = "ADD_RESERVAION_RESPONSE";
export const ADD_CREDIT_CARD_NAME = "ADD_CREDITCARD_NAME";
export const ADD_CREDIT_CARD_NUMBER = "ADD_CREDITCARD_NUMBER";
export const ADD_CREDIT_CARD_MONTH = "ADD_CREDITCARD_MONTH";
export const ADD_CREDIT_CARD_YEAR =  "ADD_CREDITCARD_YEAR";
export const ADD_CREDIT_CARD_CVV = "ADD_CREDITCARD_CVV";

export const UPDATE_RESERVATION = "UPDATE_RESERVATION";


export const DELETE_ALL_STATE = "DELET_ALL_STATE";
export const ERROR = "ERROR";
